version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_data_to_s3.py
      - zip -g deployment_package.zip lambda_mock_data.py
 
      

  post_build:
    commands:
      # Update Lambda function ProduceAirbnbBookingData with lambda_data_to_s3.py
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket s3-airbnb-landing --s3-key lambda_data_to_s3.py
      - echo "Updated Lambda function ProduceAirbnbBookingData"

      # Update Lambda function ProcessFilteredBookings with lambda_mock_data.py code
      - aws lambda update-function-code --function-name ProcessFilteredBookings --s3-bucket s3-airbnb-landing --s3-key lambda_mock_data.py
      - echo "Updated Lambda function ProcessFilteredBookings"

      - echo "Deployment complete!"

      
