version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip . -i .
      - cd ..
      - zip -g deployment_package.zip lambda_function_1.py
      - zip -g deployment_package.zip lambda_function_2.py

  post_build:
    commands:
      - echo "Uploading package to s3..."
      - aws s3 cp deployment_package.zip s3://s3-airbnb-landing/

      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket s3-airbnb-landing --s3-key deployment_package.zip
      - echo "Updated Lambda function ProduceAirbnbBookingData"

      - aws lambda update-function-code --function-name ProcessFilteredBookings --s3-bucket s3-airbnb-landing --s3-key deployment_package.zip

      - echo "Deployment complete!"
