version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      # Create deployment package directory
      - mkdir -p deployment_package

      # Package Function 1
      - echo "Packaging ProduceAirbnbBookingData..."
      - mkdir -p ProduceAirbnbBookingData
      - cp lambda_function_1.py ProduceAirbnbBookingData/
      - pip install -r ProduceAirbnbBookingData/requirements.txt -t ProduceAirbnbBookingData/
      - cd ProduceAirbnbBookingData
      - zip
      - zip -r9 ../deployment_package/ProduceAirbnbBookingData.zip .
      - cd ..

      # Package Function 2
      - echo "Packaging AirBnB-enrichment-filter..."
      - mkdir -p AirBnB-enrichment-filter
      - cp lambda_function_2.py AirBnB-enrichment-filter/
      - pip install -r AirBnB-enrichment-filter/requirements.txt -t AirBnB-enrichment-filter/
      - cd AirBnB-enrichment-filter
      - zip -r9 ../deployment_package/AirBnB-enrichment-filter.zip .
      - cd ..

      # Package Function 3
      - echo "Packaging ProcessFilteredBookings..."
      - mkdir -p ProcessFilteredBookings
      - cp lambda_function_3.py ProcessFilteredBookings/
      - pip install -r ProcessFilteredBookings/requirements.txt -t ProcessFilteredBookings/
      - cd ProcessFilteredBookings
      - zip -r9 ../deployment_package/ProcessFilteredBookings.zip .
      - cd ..

  post_build:
    commands:
      # Upload packages to S3
      - echo "Uploading packages to S3..."
      - aws s3 cp deployment_package/ProduceAirbnbBookingData.zip s3://s3-airbnb-landing/
      - aws s3 cp deployment_package/AirBnB-enrichment-filter.zip s3://s3-airbnb-landing/
      - aws s3 cp deployment_package/ProcessFilteredBookings.zip s3://s3-airbnb-landing/

      # Update Lambda functions
      - echo "Updating Lambda functions..."
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket s3-airbnb-landing --s3-key ProduceAirbnbBookingData.zip
      - aws lambda update-function-code --function-name AirBnB-enrichment-filter --s3-bucket s3-airbnb-landing --s3-key AirBnB-enrichment-filter.zip
      - aws lambda update-function-code --function-name ProcessFilteredBookings --s3-bucket s3-airbnb-landing --s3-key ProcessFilteredBookings.zip

      - echo "Deployment complete!"

artifacts:
  files:
    - deployment_package/ProduceAirbnbBookingData.zip
    - deployment_package/AirBnB-enrichment-filter.zip
    - deployment_package/ProcessFilteredBookings.zip
